import type { Metadata } from 'next';

import { DM_Sans } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';
import { TRPCReactProvider } from '@/server/trpc/client';
import '@/app/globals.css';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_INSTANCE_NAME,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang='en'>
        <body className={`${dmSans.className} antialiased`}>
          {children}
          <Toaster />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
