import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { TRPCReactProvider } from '@/server/trpc/client';
import TopBar from '@/components/header/TopBar';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_INSTANCE_NAME,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang='en'>
        <body
          className={`${dmSans.className} antialiased grid grid-rows-[auto_1fr] h-screen`}
        >
          <TopBar />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
